version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: go
      MYSQL_USER: go
      MYSQL_PASSWORD: go

  web:
    build: .
    ports:
      - '8000:8000'
    command: ./docker-startup.sh
    volumes:
      - .:/go
    depends_on:
      - db
    environment:
      - GO_ENV=dev
      - GO_ALLOWED_HOSTS=*
      - GO_EMAIL_DOMAIN=@masonlive.gmu.edu
      - GO_DB_NAME=go
      - GO_DB_USER=go
      - GO_DB_PASSWORD=go
      - GO_DB_HOST=db
      - GO_DB_PORT=3306
      - GO_EMAIL_HOST=
      - GO_EMAIL_PORT=
      - GO_EMAIL_HOST_USER=
      - GO_EMAIL_HOST_PASSWORD=
      - GO_EMAIL_FROM=
      - GO_EMAIL_TO=
      - SUPERUSER=dhaynes3
