version: '2'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python go/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/go
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: go
      MYSQL_USER: go
      MYSQL_PASSWORD: go
  